### ISSUE TITLE
install kallisto make error

### ISSUE THREAD

**Issue by YXXEMXL** [pachterlab/kallisto#130] opened 2017-03-07 08:12 UTC
Hi
I trying to install Kallisto in my ubuntu,but had an obstacle which I could not deal with.
I downloaded Kallisto from Github pages. The system I using is Ubuntu 14.04.5. I followed instructions provided in:
[https://pachterlab.github.io/kallisto/starting](url)
Firstly I made sure Requirements are met, and CMake and HDF5 are installed. I met error when running "make" in steps of Building and Installing Kallisto, which appeared to be:

`/home/name/kallisto/build$ make

[ 93%] Building CXX object src/CMakeFiles/kallisto_core.dir/weights.cpp.o
Linking CXX static library libkallisto_core.a
[ 93%] Built target kallisto_core
Scanning dependencies of target kallisto
[100%] Building CXX object src/CMakeFiles/kallisto.dir/main.cpp.o
Linking CXX executable kallisto
libkallisto_core.a(ProcessReads.cpp.o): In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int) [clone .constprop.324]':
ProcessReads.cpp:(.text+0x4e): undefined reference to `gzread'
libkallisto_core.a(ProcessReads.cpp.o): In function `kseq_read(kseq_t*)':
ProcessReads.cpp:(.text+0x259): undefined reference to `gzread'
ProcessReads.cpp:(.text+0x2c9): undefined reference to `gzread'
ProcessReads.cpp:(.text+0x492): undefined reference to `gzread'
ProcessReads.cpp:(.text+0x5db): undefined reference to `gzread'
libkallisto_core.a(ProcessReads.cpp.o):ProcessReads.cpp:(.text+0x626): more undefined references to `gzread' follow
libkallisto_core.a(ProcessReads.cpp.o): In function `SequenceReader::~SequenceReader()':
ProcessReads.cpp:(.text+0xfd4): undefined reference to `gzclose'
ProcessReads.cpp:(.text+0xfe8): undefined reference to `gzclose'
libkallisto_core.a(ProcessReads.cpp.o): In function `SequenceReader::fetchSequences(char*, int, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::string, std::allocator<std::string> >&, bool) [clone .constprop.319]':
ProcessReads.cpp:(.text+0x2d8f): undefined reference to `gzclose'
ProcessReads.cpp:(.text+0x2da8): undefined reference to `gzclose'
ProcessReads.cpp:(.text+0x2de5): undefined reference to `gzopen'
ProcessReads.cpp:(.text+0x330e): undefined reference to `gzopen'
libkallisto_core.a(ProcessReads.cpp.o): In function `SequenceReader::fetchSequences(char*, int, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::pair<char const*, int>, std::allocator<std::pair<char const*, int> > >&, std::vector<std::string, std::allocator<std::string> >&, bool)':
ProcessReads.cpp:(.text+0x374a): undefined reference to `gzclose'
ProcessReads.cpp:(.text+0x3766): undefined reference to `gzclose'
ProcessReads.cpp:(.text+0x37a9): undefined reference to `gzopen'
ProcessReads.cpp:(.text+0x3e39): undefined reference to `gzopen'
libkallisto_core.a(KmerIndex.cpp.o): In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int) [clone .constprop.369]':
KmerIndex.cpp:(.text+0x2be): undefined reference to `gzread'
libkallisto_core.a(KmerIndex.cpp.o): In function `KmerIndex::BuildTranscripts(ProgramOptions const&)':
KmerIndex.cpp:(.text+0x7e07): undefined reference to `gzopen'
KmerIndex.cpp:(.text+0x7ec3): undefined reference to `gzread'
KmerIndex.cpp:(.text+0x8006): undefined reference to `gzread'
KmerIndex.cpp:(.text+0x81f1): undefined reference to `gzread'
KmerIndex.cpp:(.text+0x881d): undefined reference to `gzread'
KmerIndex.cpp:(.text+0x8889): undefined reference to `gzclose'
/usr/local/lib/libhdf5.a(H5Zdeflate.c.o): In function `H5Z_filter_deflate':
H5Zdeflate.c:(.text+0x196): undefined reference to `inflateInit_'
H5Zdeflate.c:(.text+0x207): undefined reference to `inflate'
H5Zdeflate.c:(.text+0x22e): undefined reference to `inflateEnd'
H5Zdeflate.c:(.text+0x2cc): undefined reference to `inflateEnd'
H5Zdeflate.c:(.text+0x3bc): undefined reference to `inflateEnd'
H5Zdeflate.c:(.text+0x50e): undefined reference to `compress2'
collect2: error: ld returned 1 exit status
make[2]: *** [src/kallisto] Error 1
make[1]: *** [src/CMakeFiles/kallisto.dir/all] Error 2
make: *** [all] Error 2`

Seems like I could not find way out. I will appreciate it if you could give us hints on how to figure this out.

Thank you very much!

Ye

**Comment by pmelsted** [comment] 2017-03-07 10:45
The issue is that it is not linking to zlib. It looks like cmake is not finding zlib and yet doesn't object.

can you make sure you have zlib installed, you can try using

`sudo apt-get install zlib1g-dev`

closing this for now, but follow up on the mailing list

**Closed by pmelsted** 2017-03-07 10:45 UTC
