### ISSUE TITLE
GenomeBam error when using kallisto quant in the latest version

### ISSUE THREAD

**Issue by juychen** [pachterlab/kallisto#302] opened 2021-04-07 02:36 UTC
Hi, 

When I ran the command Kallisto quant in the latest version to generate the BAM file for the pseudo alignment. It threw a segmentation error.
But version 0.46.1 does not have the same problem.

Regards,
JY

**Comment by etrh** [comment] 2022-01-18 12:40
I'm facing the same issue with `0.46.2`. However, after downgrading to `0.46.1`, I no longer see a segmentation error.

It also looks like the newest version (`0.48.0`) might have fixed this error. However, I only tested it with one dataset. I haven't tested it yet with all of the datasets that were resulting in a segmentation error on 0.46.2 but not on 0.46.1. 

@pmelsted @Yenaled Can you confirm whether it's safe to assume that the issue with `segmentation fault - core dump` has been addressed in `0.48.0`? Thank you very much.

**Comment by Yenaled** [comment] 2022-01-18 13:43
Hi! We made several bug fixes in 0.48.0, including in genomebam (e.g. we fixed some problems with uninitialized variables that could have resulted in segfaults). Whether those fixes specifically address the problems that were causing the segfaults on your end, I can't say for sure. I can't promise that the problem is now fixed; but if you ever run into an error using genomebam again, please send me the exact commands you ran and I will look into it. I've tested genomebam on a few datasets and it seems to work well.

**Comment by Yenaled** [comment] 2022-01-18 14:06
OK, looking through previous issues of a similar nature - https://github.com/pachterlab/kallisto/issues/289 - I can confirm that this specific issue was fixed in the latest version (0.48.0). Therefore, I'm closing these issues but please open a new issue if any new issues with genomebam arise.

**Closed by Yenaled** 2022-01-18 14:06 UTC
