### ISSUE TITLE
Kallisto freezes 

### ISSUE THREAD

**Issue by olegs** [pachterlab/kallisto#95] opened 2015-12-16 09:21 UTC
We try to launch kallisto to compute tpm abundance of the following fastq.gz file. 
Unfortunally it performs em algorithm and freezes, i.e. no output for more than 6 hours.
`kallisto quant -i /mnt/stripe/Bioinformatics/data/genomes/hg19/hg19.cdna.all.fa.idx -o /mnt/stripe/Bioinformatics/data/experiments/cache/kallisto/kallisto_hg19_IMR90 cell line_SRR020295 -b 100 -t 32 --single -l 200 -s 600 /mnt/stripe/Bioinformatics/data/raw-data/roadmapepigenomics/SRX007167/SRR020295/SRR020295.fastq.gz`

As you may see from the command line above we launch kallisto for roadmap epigenomics data. http://sra.dnanexus.com/runs/SRR020292/experiments
Later we've converted it to `fastq.gz` using `fastq-dump` from `sratoolkit.2.3.3-4-centos_linux64` with --gzip argument.

```
[2015-12-15 18:17:04] [quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[2015-12-15 18:17:04] [index] k-mer length: 31
[2015-12-15 18:17:04] [index] number of targets: 196,317
[2015-12-15 18:17:04] [index] number of k-mers: 119,100,823
[2015-12-15 18:17:27] [index] number of equivalence classes: 797,045
[2015-12-15 18:17:30] [quant] running in single-end mode
[2015-12-15 18:17:30] [quant] will process file 1: /mnt/stripe/Bioinformatics/data/raw-data/roadmapepigenomics/SRX007167/SRR020295/SRR020295.fastq.gz
[2015-12-15 18:20:50] [quant] finding pseudoalignments for the reads ... done
[2015-12-15 18:20:50] [quant] processed 9,936,500 reads, 5,068,932 reads pseudoaligned
[2015-12-15 18:21:26] [   em] quantifying the abundances ... done
[2015-12-15 18:21:26] [   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```

Please note that other files are being processed correctly, so indeces are ok. Thanks a lot for the great tool, hope this will be resolved soon.

**Comment by pmelsted** [comment] 2015-12-16 09:27
Hi Oleg

Thanks for reporting this. I'll try to reproduce this in my machine using the same SRR file. Just for clarification, what is the exact fasta file you used, i.e. hg19?

- Pall

**Comment by olegs** [comment] 2015-12-16 09:33
Yep, hg19, thanks a lot!

**Comment by pmelsted** [comment] 2015-12-16 10:03
What I meant is do you have the exact URL you downloaded it from.

**Comment by olegs** [comment] 2015-12-16 10:28
Paul, hope this helps.
ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR020/SRR020295/SRR020295.sra

**Comment by pmelsted** [comment] 2015-12-16 10:30
I'm getting the SRA file right now, but which hg19 file did you use?

Also from the command line you copied it looks like you have a space in the folder name, I'm assuming this was properly escaped, since you weren't having issues with any other files.

**Comment by olegs** [comment] 2015-12-16 10:38
Here it is: ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz

**Comment by pmelsted** [comment] 2015-12-16 10:54
What is the md5sum of your fasta file? I'm not getting the same number of targets, equivalence classes and k-mers from the fasta file I just downloaded. Also with this index, the run finishes without any issues.

**Comment by olegs** [comment] 2015-12-16 12:05
Our used `Homo_sapiens.GRCh37.cdna.all.fa.gz` is slightly different, that is available at the moment, so we've backup-ed both sequence and index and will try to reproduce from scratch with sequence available by the link.

**Comment by olegs** [comment] 2015-12-16 12:49
We've tried to download hg19 fa file from the link, kallisto has built index successfully, and stuck again. I.e. it consumes CPU, but nothing happens. The latest message: 
```
[2015-12-16 16:12:54] [quant] finding pseudoalignments for the reads ... done
[2015-12-16 16:12:54] [quant] processed 9,974,284 reads, 5,013,366 reads pseudoaligned
[2015-12-16 16:13:41] [   em] quantifying the abundances ... done
[2015-12-16 16:13:41] [   em] the Expectation-Maximization algorithm ran for 1,077 rounds
```
Probably it has something to do with CPU number? How many thread did you tried? Does `kallisto` have any debug output command line key?

**Comment by pmelsted** [comment] 2015-12-16 13:08
I ran it with 4 threads. Looking at the SRR file it doesn't seem to have the same number of reads.

I'm using the file obtained with, 
`fastq-dump SRR020295 --gzip`
and an md5sum of
`MD5 (SRR020295.fastq.gz) = 10c6239cb36083be71b7d2208d93deb3`

Which doesn't match what you are seeing.

Can you run it without the bootstrap or with fewer threads, perhaps this is an issue in the multithreading of the bootstrap code.

For reference, here is what I'm getting (without bootstrap, but I ran 100 before without issues).

```
kallisto quant -i hg19.idx -o out  -t 4 -l 200 -s 600 SRR020295.fastq.gz --single                                      

[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```

**Comment by olegs** [comment] 2016-04-02 12:13
Hello @pmelsted. Recently I've done small investigation on the topic, and here are some results:

I stated with empty folder.
```
user@franklin:~/work/kallisto_github$ fastq-dump SRR020295 --gzip
Read 9936517 spots for SRR020295
Written 9936517 spots for SRR020295

user@franklin:~/work/kallisto_github$ md5sum SRR020295.fastq.gz 
10c6239cb36083be71b7d2208d93deb3  SRR020295.fastq.gz

user@franklin:~/work/kallisto_github$ wget ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz
--2016-04-02 14:02:27--  ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz
           => “Homo_sapiens.GRCh37.cdna.all.fa.gz”
Resolving ftp.ensembl.org... 193.62.203.85
Connecting to ftp.ensembl.org|193.62.203.85|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/grch37/current/fasta/homo_sapiens/cdna ... done.
==> SIZE Homo_sapiens.GRCh37.cdna.all.fa.gz ... 60898964
==> PASV ... done.    ==> RETR Homo_sapiens.GRCh37.cdna.all.fa.gz ... done.
Length: 60898964 (58M) (unauthoritative)

100%[=======================================================================================================================>] 60,898,964  5.71M/s   in 16s     

2016-04-02 14:02:45 (3.54 MB/s) - “Homo_sapiens.GRCh37.cdna.all.fa.gz” saved [60898964]
user@franklin:~/work/kallisto_github$ kallisto index -i hg19.idx Homo_sapiens.GRCh37.cdna.all.fa.gz 

[build] loading fasta file Homo_sapiens.GRCh37.cdna.all.fa.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 1401 target sequences
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 1022307 contigs and contains 101446106 k-mers 

user@franklin:~/work/kallisto_github$ ls
hg19.idx  Homo_sapiens.GRCh37.cdna.all.fa.gz  SRR020295.fastq.gz
```

After that I've tried different combinations of `-b` and `-t` parameters.
Variant you proposed worked fine:
```
user@franklin:~/work/kallisto_github$ kallisto quant -i hg19.idx -o out  -t 4 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```

Initial parameters fails as well, I mean hangs for reasonable amount of time:
```
user@franklin:~/work/kallisto_github$ kallisto quant -i hg19.idx -o out2 -b 100 -t 32 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```

No bootstrap and 32 threads works fine:
```
user@franklin:~/work/kallisto_github$ kallisto quant -i hg19.idx -o out3 -t 32 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```
This hangs:
```
user@franklin:~/work/kallisto_github$ kallisto quant -i hg19.idx -o out5 -b 2 -t 2 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
```
It' worth mentioning that the following command line: hangs on another phase:
```
user@franklin:~/work/kallisto_github$ kallisto quant -i hg19.idx -o out6 -b 1 -t 1 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
[bstrp] running EM for the bootstrap: 1
```

Some information about the system:
32CPUs
```
user@franklin:~/work/kallisto_github$ kallisto version
kallisto, version 0.42.3

user@franklin:~/work/kallisto_github$ uname -a
Linux unit-503 4.5.0-1.el6.elrepo.x86_64 #1 SMP Mon Mar 14 12:11:26 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Unfortunally, `Sleuth` requires bootstrap  results, so that this is still an issue.
Please let me know if you need any questions.
Best regards,
Oleg

**Comment by pmelsted** [comment] 2016-04-03 20:14
I've tried to reproduce this using the exact same commands, same input and index on a mac and linux (ubuntu) system. Both the most recent version and 0.42.3 and I don't see anything.

When you say it hangs or freezes, does it finish the run or not. For how long does the pseudoalignment, EM and bootstrap take approximately. I saw about 2 minutes on our system for all of the above and 4.5 minutes for 100 bootstraps with 32 threads.

Do you see this also on the latest version?

**Comment by olegs** [comment] 2016-04-04 09:55
Approximately 50 min, and running without any progress in console. It this OK?
```
user@franklin:~/work/kallisto_github$ time kallisto quant -i hg19.idx -o out2 -b 100 -t 32 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
^C

real	49m48.727s
user	265m17.746s
sys	509m57.732s
```

**Comment by olegs** [comment] 2016-04-04 09:56
We'll try to reproduce it on Ubuntu as well, main system is CentOS.

**Comment by pmelsted** [comment] 2016-04-04 10:02
It might be centos specific, I'll try to reproduce on another system. Did
you use the binary or compile from source? In which case, what compiler and
version did you have?

**Comment by atsky** [comment] 2016-04-04 10:52
On my Ubuntu machine
```
atsky@munit-030:~/work/kalisto_test$ time ./kallisto_linux-v0.42.3/kallisto quant -i hg19.idx -o out2 -b 100 -t 32 -l 200 -s 600 SRR020295.fastq.gz --single

[quant] fragment length distribution is truncate gaussian with mean = 200, sd = 600
Warning: you asked for 32, but only 8 cores on the machine
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
[bstrp] number of EM bootstraps complete: 100


real	19m46.999s
user	111m57.976s
sys	0m12.312s

```

**Comment by pmelsted** [comment] 2016-04-04 11:20
I just ran this on my centos system

```
uname -a
Linux compute-0-7.local 2.6.32-279.14.1.el6.x86_64 #1 SMP Tue Nov 6
23:43:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

and it finished in 6 minutes, both for version 0.42.3 and 0.42.4.

When you specify using multiple threads do you see all/most of them being
used during pseudoalignment and the bootstrap phase?

**Comment by atsky** [comment] 2016-04-04 15:40
@pmelsted, I had some other process run in parallel, so it finished in reasonable time.

**Comment by olegs** [comment] 2016-04-05 07:53
Good news: we've updated kallisto to 0.42.4 and kallisto managed to finish. Looks like a threading issue.
```
user@franklin:~/work/kallisto_github$ time kallisto quant -i hg19.idx -o out -b 100 -t 32 -l 200 -s 600 SRR020295.fastq.gz --single 

[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 600
[index] k-mer length: 31
[index] number of targets: 180,253
[index] number of k-mers: 101,446,106
[index] number of equivalence classes: 693,993
[quant] running in single-end mode
[quant] will process file 1: SRR020295.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 9,936,517 reads, 5,000,809 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,223 rounds
[bstrp] number of EM bootstraps complete: 100


real	4m31.920s
user	107m26.847s
sys	0m59.679s
```
This was the only task on machine, will try on machine with high load.

**Comment by olegs** [comment] 2016-04-05 08:22
Even with high load, everything works fine, thank you!

**Comment by pmelsted** [comment] 2016-04-05 12:19
Great, closing this issue. There is also a new version 0.42.5 released yesterday.

**Closed by pmelsted** 2016-04-05 12:19 UTC

**Comment by vasanthmandla** [comment] 2018-02-14 04:28
I am having the same issue. I am working with Kallisto 0.44.0. Kallisto quant is not performing the further steps after:
[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 195
[index] number of k-mers: 2,666,294,845
[index] number of equivalence classes: 1,867,554

command: /home/vmandla/Tuxedo/kallisto_linux-v0.44.0/kallisto quant -i ./refindex.idx -o ./Ctrl1/kallisto/ -b 100 -t 12 ../Control/Ctrl1-R1.fastq ../Control/Ctrl1-R2.fastq

**Comment by pmelsted** [comment] 2018-02-14 09:20
Judging by the number of k-mers and number of targets it looks like you ran this on a human (or mammalian) genome rather than a transcriptome. In that case kallisto will need a lot of memory and has probably run out and using swap space.

**Comment by vasanthmandla** [comment] 2018-02-14 17:36
Yes, iam working on the human genome. I am currently working in the cluster so memory is not an issue. Kindly, suggest the minimum number of threads that I should use. Thanks in advance.

**Comment by lynnyi** [comment] 2018-02-14 17:43
Hi,

kallisto works on the transcriptome instead of the genome. Download the transcriptome file instead and make an index with that.

Best,
Lynn

**Comment by vasanthmandla** [comment] 2018-02-15 22:21
Thanks
