### ISSUE TITLE
kallisto bus randomly processes only a subset of the reads

### ISSUE THREAD

**Issue by slinnarsson** [pachterlab/kallisto#225] opened 2019-08-22 12:57 UTC
I suspect this might be a concurrency bug. 

I have a pair of fastq files with 137,592,951 reads. I verify the number of reads using `wc -l`:

```
$ gzip -dc /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R1_001.fastq.gz | grep "+$" | wc -l
 137592951
```

Often when I run `kallisto bus` on these files, it will process all the reads. But occasionally, kallisto only processes a seemingly random subset. For example, in this case 23,533,848 reads:

```
2019-08-22 14:40:57,437 [INFO] kallisto bus -i /Users/stelin/kallisto_GRCh38/human_GRCh38_gencode.v31/gencode.v31.fragments.idx -o /var/folders/q2/rd2c51f14yd_xm78k8zrchy0wb1m9h/T/tmp453ef25v -x 10xv2 -t 6 /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R1_001.fastq.gz /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R2_001.fastq.gz
2019-08-22 14:40:57,485 [INFO] [index] k-mer length: 31
2019-08-22 14:40:57,487 [INFO] [index] number of targets: 845,338
2019-08-22 14:40:57,489 [INFO] [index] number of k-mers: 178,605,364
2019-08-22 14:41:23,057 [INFO] [index] number of equivalence classes: 4,191,221
2019-08-22 14:41:39,450 [INFO] [quant] will process sample 1: /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R1_001.fastq.gz
2019-08-22 14:41:39,451 [INFO]                                /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R2_001.fastq.gz
2019-08-22 14:43:37,942 [INFO] [quant] finding pseudoalignments for the reads ... done
2019-08-22 14:43:37,953 [INFO] [quant] processed 23,533,848 reads, 17,778,425 reads pseudoaligned
```

The same phenomenon occurs on other files, so there's nothing special about these. It happens about 20% of the time, I estimate.

This is kallisto v0.46.0 on a MacBook Pro (6 cores) running macOS 10.13.6.

EDIT: rerunning the exact same command, with the same untouched index and fastq files, half an hour later:

```
2019-08-22 15:00:36,846 [INFO] kallisto bus -i /Users/stelin/kallisto_GRCh38/human_GRCh38_gencode.v31/gencode.v31.fragments.idx -o /var/folders/q2/rd2c51f14yd_xm78k8zrchy0wb1m9h/T/tmp_68whvdt -x 10xv2 -t 6 /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R1_001.fastq.gz /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R2_001.fastq.gz
2019-08-22 15:00:36,880 [INFO] [index] k-mer length: 31
2019-08-22 15:00:36,882 [INFO] [index] number of targets: 845,338
2019-08-22 15:00:36,883 [INFO] [index] number of k-mers: 178,605,364
2019-08-22 15:01:00,748 [INFO] [index] number of equivalence classes: 4,191,221
2019-08-22 15:01:22,074 [INFO] [quant] will process sample 1: /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R1_001.fastq.gz
2019-08-22 15:01:22,076 [INFO]                                /Users/stelin/kallisto_GRCh38/HL73JBCXY/10X_17_029_S2_L002_R2_001.fastq.gz
2019-08-22 15:15:25,839 [INFO] [quant] finding pseudoalignments for the reads ... done
2019-08-22 15:15:25,856 [INFO] [quant] processed 137,592,951 reads, 104,132,700 reads pseudoaligned
```

**Comment by pmelsted** [comment] 2019-08-22 14:29
Can you share the fastq files, I can check if I can recreate the issue on my machine. 

- Is the BUS file output the same, in which case the number reported is wrong
- Does `gzcat file.fastq.gz | wc -l` always report the same value if you run it a few times and are there any warnings (this can happen with malformed gzip files)
- Does the issue also happen with running in quant mode for the R2 file and using `--single-end` (which makes no sense biologically but tests more or less the same process)

**Comment by slinnarsson** [comment] 2019-08-23 12:10
The BUS output corresponds to the reported number of reads, not the correct total.

I actually got paranoid that my disk is failing (because the whole computer froze a couple of times lately), so I did a `fsck` but which reported everything was normal. It's still possible that my disk is failing, so maybe you should just leave this issue here unless somebody else has the same problem.

I'll upload the fastq files to google cloud and send you a link.

**Comment by pmelsted** [comment] 2019-08-28 14:27
I have run this in loop, 21 times on my machine (quadcore mac, os 10.3.6, kallisto version v0.46.0) using 4 threads on the same input, it always reports the same output. I cannot reproduce this error.

I think that for some reason, kallisto is receiving info that one of the files is done reading and stops processing the files. This is consistent with the bus output containing the same number of reads as reported in the terminal.

I'm closing this for now, but feel free to reopen if you run into this on a different machine.

**Closed by pmelsted** 2019-08-28 14:27 UTC
