### ISSUE TITLE
How to get the number of "reads pseudoaligned" from the results?

### ISSUE THREAD

**Issue by kalugny** [pachterlab/kallisto#150] opened 2017-12-04 14:19 UTC
Hi and thanks for a great library.
We've ran `kallisto` on many files, and didn't save the `stdout` prints.

Is there a way to get the number of "reads pseudoaligned" from the `h5` file?

I noticed that the number in the code is not saved anywhere:
https://github.com/pachterlab/kallisto/blob/1e0e11288558ad88af198ec4f5302129c249b44f/src/ProcessReads.cpp#L191

but maybe there's a way to deduce it from something else?

Thanks,
 Yuval

**Comment by mschilli87** [comment] 2017-12-04 14:34
How about summing up the number of reads assigned to each transcript? :wink:

**Comment by renozao** [comment] 2017-12-04 15:43
Wondering if this a general result, or just due to low depth/luck.
Doesn't kallisto allow by design, for a read to map to multiple transcript? 
Hence a read can participate to multiple `est_count` values.
Thanks

**Comment by mschilli87** [comment] 2017-12-04 16:39
@renozao: Yes, but AFAIK, the read is assigned *partionally*. That's why the `est_counts` for a single transcript aren't nessecarily integers, but their sum is (as each read counts `1` in total, distributed in fractions to all matchting transcripts according to the EM results). I don't have time to check the formulas/code right now but I'm pretty certain this should hold true in general.

**Comment by maximilianh** [comment] 2017-12-04 16:59
This happened to me, too. It would be nice if kallisto wrote the few
essential stats to a little file instead of stdout.

**Comment by renozao** [comment] 2017-12-06 09:45
@mschilli87 makes sense. That's great.
I agree that saving more stats into the output json file would be helpful. 
Thanks!

**Comment by winni2k** [comment] 2018-03-01 14:00
It looks like kallisto version `0.44.0` now has a an entry in the output json called "n_pseudoaligned" and that number is identical to the rounded sum of of the `est_counts` column in my data set.  Can this issue be closed?

**Closed** 2018-11-26 00:57 UTC
